@echo off
SET BIT=

SET TORCH_DYNAMIC_MessageboxAtAttach=

SET CORECLR_PROFILER=
SET CORECLR_ENABLE_PROFILING=
SET CORECLR_PROFILER_PATH_32=
SET CORECLR_PROFILER_PATH_64=
SET COMPLUS_ProfAPI_ProfilerCompatibilitySetting=
SET TORCHCORE_CALLBACK_HOME=

SET COR_PROFILER=
SET COR_ENABLE_PROFILING=
SET COR_PROFILER_PATH_32=
SET COR_PROFILER_PATH_64=
SET COMPLUS_ProfAPI_ProfilerCompatibilitySetting=
SET TORCH_CALLBACK_HOME=

echo Profiler is off


